//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionUsuarioToRol
    {
        public int ID { get; set; }
        public int ID_AccionUsuario { get; set; }
        public int ID_RolUsuario { get; set; }
        public bool SoloLectura { get; set; }
        public bool LecturaYEscritura { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual UsuarioAccion UsuarioAccion { get; set; }
        public virtual UsuarioRol UsuarioRol { get; set; }
    }
}
