//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ads()
        {
            this.CategoriasPorAds = new HashSet<CategoriasPorAds>();
        }
    
        public long ID { get; set; }
        public long ID_Empresa { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public short Largo { get; set; }
        public short Alto { get; set; }
        public string ColorPrincipal { get; set; }
        public string ColorSecundario { get; set; }
        public string ColorTexto { get; set; }
        public string Imagen { get; set; }
        public bool Principal { get; set; }
        public bool Destacado { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime TS { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasPorAds> CategoriasPorAds { get; set; }
    }
}
