//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WhiteAdsEntities : DbContext
    {
        public WhiteAdsEntities()
            : base("name=WhiteAdsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionUsuarioToRol> AccionUsuarioToRol { get; set; }
        public virtual DbSet<Ads> Ads { get; set; }
        public virtual DbSet<Banco> Banco { get; set; }
        public virtual DbSet<Beneficio> Beneficio { get; set; }
        public virtual DbSet<Beneficio_Detalle> Beneficio_Detalle { get; set; }
        public virtual DbSet<Calificacion> Calificacion { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaConfiguraciones> EmpresaConfiguraciones { get; set; }
        public virtual DbSet<EmpresaHorarios> EmpresaHorarios { get; set; }
        public virtual DbSet<EmpresaHorariosEspeciales> EmpresaHorariosEspeciales { get; set; }
        public virtual DbSet<EmpresaRedesSociales> EmpresaRedesSociales { get; set; }
        public virtual DbSet<EmpresaRubro> EmpresaRubro { get; set; }
        public virtual DbSet<EmpresaSucursal> EmpresaSucursal { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<FormaPagoEmpresa> FormaPagoEmpresa { get; set; }
        public virtual DbSet<FormaPagoVendedor> FormaPagoVendedor { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<InstitucionSocial> InstitucionSocial { get; set; }
        public virtual DbSet<InstitucionSocialConfiguraciones> InstitucionSocialConfiguraciones { get; set; }
        public virtual DbSet<InstitucionSocialRedesSociales> InstitucionSocialRedesSociales { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Plan_Caracteristica> Plan_Caracteristica { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<RedesSociales> RedesSociales { get; set; }
        public virtual DbSet<UserSession> UserSession { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioAccion> UsuarioAccion { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VendedorConfiguraciones> VendedorConfiguraciones { get; set; }
        public virtual DbSet<VendedorRedesSociales> VendedorRedesSociales { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<EmpresaCuenta> EmpresaCuenta { get; set; }
        public virtual DbSet<InstitucionSocialCuenta> InstitucionSocialCuenta { get; set; }
        public virtual DbSet<VendedorCuenta> VendedorCuenta { get; set; }
        public virtual DbSet<CategoriasPorAds> CategoriasPorAds { get; set; }
        public virtual DbSet<AdsCategoria> AdsCategoria { get; set; }
    }
}
