//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Ads = new HashSet<Ads>();
            this.Calificacion = new HashSet<Calificacion>();
            this.EmpresaConfiguraciones = new HashSet<EmpresaConfiguraciones>();
            this.EmpresaHorarios = new HashSet<EmpresaHorarios>();
            this.EmpresaHorariosEspeciales = new HashSet<EmpresaHorariosEspeciales>();
            this.EmpresaRedesSociales = new HashSet<EmpresaRedesSociales>();
            this.EmpresaSucursal = new HashSet<EmpresaSucursal>();
            this.FormaPagoEmpresa = new HashSet<FormaPagoEmpresa>();
            this.Horarios = new HashSet<Horarios>();
            this.Ventas = new HashSet<Ventas>();
            this.EmpresaCuenta = new HashSet<EmpresaCuenta>();
        }
    
        public long ID { get; set; }
        public int ID_Rubro { get; set; }
        public int ID_Plan { get; set; }
        public string RazonSocial { get; set; }
        public string CUIT { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string PerfilLogo { get; set; }
        public string PerfilCabecera { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public long ID_Ciudad { get; set; }
        public string Mapa_Latitud { get; set; }
        public string Mapa_Longitud { get; set; }
        public string W3w { get; set; }
        public string GoogleMaps { get; set; }
        public string Web { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool MostrarCalificaciones { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime TS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ads> Ads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual EmpresaRubro EmpresaRubro { get; set; }
        public virtual Plan Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaConfiguraciones> EmpresaConfiguraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaHorarios> EmpresaHorarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaHorariosEspeciales> EmpresaHorariosEspeciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaRedesSociales> EmpresaRedesSociales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaSucursal> EmpresaSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaPagoEmpresa> FormaPagoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaCuenta> EmpresaCuenta { get; set; }
    }
}
