//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaPagoVendedor
    {
        public long ID { get; set; }
        public int ID_FormaPago { get; set; }
        public long ID_Vendedor { get; set; }
        public int Prioridad { get; set; }
        public string Titular { get; set; }
        public string Numero { get; set; }
        public string Documento { get; set; }
        public string Entidad { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
    
        public virtual FormaPago FormaPago { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
