//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitucionSocial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitucionSocial()
        {
            this.Beneficio = new HashSet<Beneficio>();
            this.InstitucionSocialConfiguraciones = new HashSet<InstitucionSocialConfiguraciones>();
            this.InstitucionSocialRedesSociales = new HashSet<InstitucionSocialRedesSociales>();
            this.InstitucionSocialCuenta = new HashSet<InstitucionSocialCuenta>();
        }
    
        public long ID { get; set; }
        public string RazonSocial { get; set; }
        public string CUIT { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string PerfilLogo { get; set; }
        public string PerfilCabecera { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public long ID_Ciudad { get; set; }
        public string Mapa_Latitud { get; set; }
        public string Mapa_Longitud { get; set; }
        public string Web { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime TS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficio> Beneficio { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitucionSocialConfiguraciones> InstitucionSocialConfiguraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitucionSocialRedesSociales> InstitucionSocialRedesSociales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitucionSocialCuenta> InstitucionSocialCuenta { get; set; }
    }
}
