//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSApp.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsSent
    {
        public long ID { get; set; }
        public int NewsID { get; set; }
        public int UserGroupId { get; set; }
        public System.DateTime SentDate { get; set; }
    
        public virtual News News { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
