//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int ID { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string CodigoTrx { get; set; }
        public string TraceTrx { get; set; }
        public Nullable<System.DateTime> FechaCrecion { get; set; }
        public Nullable<int> Proveedor { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
