//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedesSociales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RedesSociales()
        {
            this.EmpresaRedesSociales = new HashSet<EmpresaRedesSociales>();
            this.InstitucionSocialRedesSociales = new HashSet<InstitucionSocialRedesSociales>();
            this.VendedorRedesSociales = new HashSet<VendedorRedesSociales>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Icono { get; set; }
        public string RootURL { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime TS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaRedesSociales> EmpresaRedesSociales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitucionSocialRedesSociales> InstitucionSocialRedesSociales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendedorRedesSociales> VendedorRedesSociales { get; set; }
    }
}
