//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public System.Guid UserSessionGUID { get; set; }
        public int ID_Usuario { get; set; }
        public System.DateTime UltimoAccesso { get; set; }
        public Nullable<int> UltimaTrx { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
