//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSApp.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersByUserGroup
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int UserGroupID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
        public virtual User User { get; set; }
    }
}
