//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.UserSession = new HashSet<UserSession>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public Nullable<int> AuthenticationMode { get; set; }
        public string Pwd { get; set; }
        public string SaltKey { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> UltimoAcceso { get; set; }
        public Nullable<int> ID_RolUsuario { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSession { get; set; }
        public virtual UsuarioRol UsuarioRol { get; set; }
    }
}
