//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendedorCuenta
    {
        public int ID { get; set; }
        public long ID_Vendedor { get; set; }
        public decimal Monto { get; set; }
        public decimal MontoBloqueado { get; set; }
        public decimal MontoGastado { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Vendedor Vendedor { get; set; }
    }
}
