//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteRaven.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public long ID { get; set; }
        public long ID_Empresa { get; set; }
        public long ID_Vendedor { get; set; }
        public string Periodo { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public decimal MontoACobrar { get; set; }
        public decimal MontoAPagar { get; set; }
        public decimal MontoSocial { get; set; }
        public bool Cobrado { get; set; }
        public bool Pagado { get; set; }
        public System.DateTime TS { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
