//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSApp.Svc.AvlServiceTest {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://avl.integrarsi.com.ar", ConfigurationName="AvlServiceTest.AvlSoap")]
    public interface AvlSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://avl.integrarsi.com.ar/ObtenerPosicionActual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerPosicionActual(int idServicio, string idDispositivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://avl.integrarsi.com.ar/ObtenerPosicionActual", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerPosicionActualAsync(int idServicio, string idDispositivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://avl.integrarsi.com.ar/ObtenerRegionesActuales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerRegionesActuales(int idServicio, string idDispositivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://avl.integrarsi.com.ar/ObtenerRegionesActuales", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerRegionesActualesAsync(int idServicio, string idDispositivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://avl.integrarsi.com.ar/ObtenerRegionesActualesPorCoordenada", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerRegionesActualesPorCoordenada(int idServicio, double latitud, double longitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://avl.integrarsi.com.ar/ObtenerRegionesActualesPorCoordenada", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerRegionesActualesPorCoordenadaAsync(int idServicio, double latitud, double longitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AvlSoapChannel : SOSApp.Svc.AvlServiceTest.AvlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AvlSoapClient : System.ServiceModel.ClientBase<SOSApp.Svc.AvlServiceTest.AvlSoap>, SOSApp.Svc.AvlServiceTest.AvlSoap {
        
        public AvlSoapClient() {
        }
        
        public AvlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AvlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AvlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AvlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ObtenerPosicionActual(int idServicio, string idDispositivo) {
            return base.Channel.ObtenerPosicionActual(idServicio, idDispositivo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerPosicionActualAsync(int idServicio, string idDispositivo) {
            return base.Channel.ObtenerPosicionActualAsync(idServicio, idDispositivo);
        }
        
        public System.Data.DataTable ObtenerRegionesActuales(int idServicio, string idDispositivo) {
            return base.Channel.ObtenerRegionesActuales(idServicio, idDispositivo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerRegionesActualesAsync(int idServicio, string idDispositivo) {
            return base.Channel.ObtenerRegionesActualesAsync(idServicio, idDispositivo);
        }
        
        public System.Data.DataTable ObtenerRegionesActualesPorCoordenada(int idServicio, double latitud, double longitud) {
            return base.Channel.ObtenerRegionesActualesPorCoordenada(idServicio, latitud, longitud);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerRegionesActualesPorCoordenadaAsync(int idServicio, double latitud, double longitud) {
            return base.Channel.ObtenerRegionesActualesPorCoordenadaAsync(idServicio, latitud, longitud);
        }
    }
}
